version: 2.1
executors:
  "gofmt":
    docker:
      - image: golang:1.11
  "previous":
    docker:
      - image: golang:1.11
  "stable":
    docker:
      - image: golang:1.12
  "tip":
    docker:
      - image: golang:tip

commands:
  install:
    description: "Install prerequisites"
    parameters:
      protoc_version:
        type: string
        default: "3.1.0"
      protoc_gen_gogofaster_tag:
        type: string
        default: "v0.5"
      stringer_rev:
        type: string
        default: "25101aadb97aa42907eee6a238d6d26a6cb3c756"
      cachebust:
        type: string
        default: "1"
    steps:
      - restore_cache:
          key: "protoc-<<parameters.protoc_version>>_gogofaster-<<parameters.protoc_gen_gogofaster_tag>>_stringer-<<parameters.stringer_rev>>_<<parameters.cachebust>>"
      - run:
          name: protoc
          command: |
            if ! [ -d /opt/protoc ]; then
              apt-get -q update
              apt-get install -yq unzip
              mkdir /opt/protoc
              wget -O/tmp/protoc.zip https://github.com/google/protobuf/releases/download/v<<parameters.protoc_version>>/protoc-<<parameters.protoc_version>>-linux-x86_64.zip
              unzip /tmp/protoc.zip -d /opt/protoc
            fi
      - run:
          name: protoc-gen-gogofaster
          command: |
            if ! [ -x $GOPATH/bin/protoc-gen-gogofaster ] ; then
              go get -d -v github.com/gogo/protobuf/protoc-gen-gogofaster
              cd $GOPATH/src/github.com/gogo/protobuf
              git fetch
              git reset --hard v0.5
              go install github.com/gogo/protobuf/protoc-gen-gogofaster
            fi
      - run:
          name: gojson
          command: |
            if ! [ -x $GOPATH/bin/gojson ] ; then
              go get -u github.com/ChimeraCoder/gojson/gojson
            fi
      - run:
          name: dep
          command: |
            if ! [ -x $GOPATH/bin/dep ] ; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            fi
      - run:
          name: stringer
          command: |
            if ! [ -x $GOPATH/bin/stringer ] ; then
              go get -u -u golang.org/x/tools/cmd/stringer
              cd $GOPATH/src/golang.org/x/tools/cmd/stringer
              git reset --hard <<parameters.stringer_rev>>
              go install
            fi
      - save_cache:
          key: "protoc-<<parameters.protoc_version>>_gogofaster-<<parameters.protoc_gen_gogofaster_tag>>_stringer-<<parameters.stringer_rev>>_<<parameters.cachebust>>"
          paths:
            - /opt/protoc
            - /go/bin/protoc-gen-gogofaster
            - /go/src/github.com/gogo/protobuf
            - /go/bin/dep
            - /go/bin/stringer
  fetch_and_build_latest_go:
    description: "Builds the latest version of go from source"
    steps:
      - run:
          name: create datestamp
          command: |
            echo go-master-$(date +%Y-%m-%d) | tee /tmp/go-version
      - restore_cache:
          key: |
            {{ checksum "/tmp/go-version" }}
      - run:
          name: get latest master
          command: |
            mv /usr/local/go /usr/local/go-stable
            wget -O/tmp/go-master.tgz https://github.com/golang/go/archive/master.tar.gz
            tar -C /tmp -zxf /tmp/go-master.tgz
            mv /tmp/go-master /usr/local/go
            export GOSRC=/usr/local/go
            export GOROOT=$GOSRC
            export GOROOT_BOOTSTRAP=/usr/local/go-stable
            export GOBUILD=$GOSRC/src
            cp /tmp/go-version $GOROOT/VERSION
            cd $GOBUILD
            ./make.bash
      - save_cache:
          key: |
            {{ checksum "/tmp/go-version" }}
          paths:
            - /usr/local/go
  test:
    description: "Run the tests"
    steps:
      - run:
          name: go test
          command: go test -race -v -timeout 60s ./...

jobs:
  success:
    docker:
      - image: alpine:latest
    steps:
      - run: echo yay

  code_hygiene:
    executor:
      name: gofmt
    working_directory: /go/src/github.com/stripe/veneur
    steps:
      - install
      - checkout
      - run:
          name: go generate
          command: |
            export PATH=$PATH:/opt/protoc/bin
            go generate
      - run: "dep check"
      - run:
          name: "gofmt"
          command: |
            mv vendor /tmp/veneur-vendor
            gofmt -w .
            mv /tmp/veneur-vendor ./vendor
      - run:
          name: "check if any files changed"
          command: |
            git add .
            env PAGER=cat git diff --cached
            git diff-index --cached --exit-code HEAD

  test_stable:
    executor:
      name: stable
    working_directory: /go/src/github.com/stripe/veneur
    steps:
    - checkout
    - test

  test_previous:
    executor:
      name: previous
    working_directory: /go/src/github.com/stripe/veneur
    steps:
      - checkout
      - test

  test_tip:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/stripe/veneur
    environment:
      GO111MODULE: auto
    steps:
      - fetch_and_build_latest_go
      - checkout
      - test

workflows:
  version: 2
  continuous_integration:
    jobs:
      - code_hygiene
      - test_stable
      - test_previous
      - test_tip
      - success:
          requires:
          - code_hygiene
          - test_stable
          - test_previous
          - test_tip
