version: 2.1
executors:
  "previous":
    docker:
      - image: golang:1.11
  "stable":
    docker:
      - image: golang:1.12
  "tip":
    docker:
      - image: golang:tip

commands:
  install:
    description: "Install prerequisites"
    parameters:
      gofmt_version:
        type: string
        default: "1.11"
      protoc_version:
        type: string
        default: "3.1.0"
      protoc_gen_gogofaster_tag:
        type: string
        default: "v0.5"
      stringer_rev:
        type: string
        default: "25101aadb97aa42907eee6a238d6d26a6cb3c756"
    steps:
      - restore_cache:
          key: "gofmt-<<parameters.gofmt_version>>_protoc-<<parameters.protoc_version>>_gogofaster-<<parameters.protoc-gen-gogofaster_tag>>_stringer-<<parameters.stringer_rev>>"
      - run:
          name: protoc
          command: |
            if ! [ -d /opt/protoc ]; then
              apt-get -q update
              apt-get install -yq unzip
              mkdir /opt/protoc
              wget -O/tmp/protoc.zip https://github.com/google/protobuf/releases/download/v<<parameters.protoc_version>>/protoc-<<parameters.protoc_version>>-linux-x86_64.zip
              unzip /tmp/protoc.zip -d /opt/protoc
            fi
      - run:
          name: gofmt
          command: |
            if ! [ -d /opt/gofmt ] ; then
              mkdir /opt/gofmt
              wget -O/tmp/go.tgz https://storage.googleapis.com/golang/go<<parameters.gofmt_version>>.linux-amd64.tar.gz
              tar -C /opt/gofmt -xvf /tmp/go.tgz go/bin/gofmt
            fi
      - run:
          name: protoc-gen-gogofaster
          command: |
            if ! [ -x $GOPATH/bin/protoc-gen-gogofaster ] ; then
              go get -d -v github.com/gogo/protobuf/protoc-gen-gogofaster
              cd $GOPATH/src/github.com/gogo/protobuf
              git fetch
              git reset --hard v0.5
              go install github.com/gogo/protobuf/protoc-gen-gogofaster
            fi
      - run:
          name: gojson
          command: |
            if ! [ -x $GOPATH/bin/gojson ] ; then
              go get -u github.com/ChimeraCoder/gojson/gojson
            fi
      - run:
          name: dep
          command: |
            if ! [ -x $GOPATH/bin/dep ] ; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            fi
      - run:
          name: stringer
          command: |
            if ! [ -x $GOPATH/bin/stringer ] ; then
              go get -u -u golang.org/x/tools/cmd/stringer
              cd $GOPATH/src/golang.org/x/tools/cmd/stringer
              git reset --hard <<parameters.stringer_rev>>
              go install
            fi
      - save_cache:
          key: "gofmt-<<parameters.gofmt_version>>_protoc-<<parameters.protoc_version>>_gogofaster-<<parameters.protoc-gen-gogofaster_tag>>_stringer-<<parameters.stringer_rev>>"
          paths:
            - /opt/protoc
            - /opt/gofmt
            - /go/bin/protoc-gen-gogofaster
            - /go/bin/dep
            - /go/bin/stringer



jobs:
  build:
    docker:
      # specify the version
      - image: golang:1.11

    working_directory: /go/src/github.com/stripe/veneur
    steps:
      - install
      - checkout

      - run: go test -race -v -timeout 60s ./...
